version: "3.5"

x-base: &base
  image: car_app
  volumes:
    - .:/project/app
    - static:/project/static
    - media:/project/media
  depends_on:
    - postgres
    - redis
  env_file: .env
  restart: on-failure
  stdin_open: true
  tty: true

services:
  postgres:
    image: postgres:10.7-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.3-alpine

  django:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: runserver
    ports:
      - "8000:8000"

  bootstrap:
    <<: *base
    command: manage bootstrap

  celery:
    <<: *base
    command: celery

volumes:
  pg-data:
  static:
  media:
