# Generated by Django 2.2.1 on 2020-03-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('registration_no', models.CharField(max_length=7, unique=True, verbose_name='registration number')),
                ('brand', models.CharField(blank=True, default='', max_length=60, verbose_name='brand of a car')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='departments.Department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'ordering': ('-created',),
            },
        ),
    ]
